config/routes.rb
Rails.application.routes.draw do
  get "/up", to: proc { [200, { "Content-Type" => "text/plain" }, ["OK"]] }

  root to: 'pages#home'

  get 'domaines-expertise', to: 'pages#domaines_expertise'
  get 'cabinet', to: 'pages#cabinet'
  get 'contact', to: 'pages#contact'
  get 'mentions-legales', to: 'pages#mentions_legales'

  resources :contacts, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact
  include ActiveModel::Model
  attr_accessor :name, :email, :body
  validates :name, :email, :body, presence: true
end

app/models/contact_info.rb
class ContactInfo
  include ActiveModel::Model
  include ActiveModel::Attributes

  attribute :first_name, :string
  attribute :last_name, :string
  attribute :email, :string
  attribute :phone, :string
  attribute :fax, :string
  attribute :street_number, :string
  attribute :street_name, :string
  attribute :zip_code, :string
  attribute :city, :string
  attribute :linkedin_url, :string

  def self.current
    new(
      first_name: 'Yuma',
      last_name: 'Fruneau',
      email: 'avocat@fruneau-avocat.com',
      phone: '09 81 29 56 39',
      fax: nil,
      street_number: '18',
      street_name: 'Rue Bonneterie',
      zip_code: '13002',
      city: 'Marseille',
      linkedin_url: 'https://www.linkedin.com/in/yuma-fruneau-b44b698b/'
    )
  end

  def google_map_url
    "https://www.google.com/maps?q=#{street_number}+#{street_name},+#{zip_code}+#{city}&output=embed"
  end

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :contact_info

  private

  def contact_info
    @contact_info = ContactInfo.current
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)

    if recaptcha_valid? && @contact.valid?
      send_mail!

      flash[:notice] = "Votre message a été envoyé avec succès."
      redirect_to root_path
    else
      flash[:alert] = "Une erreur c'est produite, veuillez réessayer."
      render :new, status: :unprocessable_entity
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :body)
  end

  def recaptcha_valid?
    Recaptcha.configuration.site_key.present? ? verify_recaptcha(model: @contact) : true
  end

  def send_mail!
    Mailer.call(contact: @contact)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def domaines_expertise
  end

  def cabinet
  end

  def contact
  end

  def mentions_legales
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def copiright_year_update
    Time.current.year
  end
end

app/helpers/phone_email_helper.rb
module PhoneEmailHelper
  def phone_link
    link_to @contact_info.phone, "tel:#{@contact_info.phone.squish}", class: 'link_email_phone'
  end

  def email_link
    link_to @contact_info.email, "mailto:#{@contact_info.email}", class: 'link_email_phone'
  end
end

app/views/contacts/_contact-form.html.erb
<div id="form-main" data-controller="contact-form" data-contact-form-target="form">
  <div id="form-div" data-contact-form-target="overlay" data-contact-form-target="content" data-action="click->contact-form#close">
    <div class="form" id="form1">

      <h2 class="zi500">Contactez-nous :</h2>
      <div id="underliner-contact-form"></div>
      <%= simple_form_for contact, data: { turbo_frame: "_top" } do |f| %>
        <%= f.input :name, label: false, placeholder: 'Votre nom*', input_html: { class: 'feedback-input' } %>
        <%= f.input :email, label: false, placeholder: 'Votre e-mail*', input_html: { class: 'feedback-input' } %>
        <%= f.input :body, label: false, placeholder: 'Votre message*', as: :text, :input_html => { :cols => 6, :rows => 300, class: 'feedback-input' } %>
        <% if Recaptcha.configuration.site_key.present? %>
          <div class="recaptcha-tags">
            <%= recaptcha_tags %>
          </div>
        <% end %>
        <%= f.submit 'ENVOYER', class: 'button-blue', id: 'sending-btn', data: { action: "turbo:submit-end->contact-form#messageSent" } %>
      <% end %>

    </div>
  </div>
</div>

app/views/contacts/new.html.erb
<%= render 'contact-form', contact: @contact %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @contact_info.full_name %> | Avocate |</title>
    <%# Security : %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# Favicon : %>
    <%= favicon_link_tag 'favicon.ico' %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Maître Fruneau intervient en droit des étrangers (recours OQTF, demande de titre de séjour, naturalisation, regroupement familial), en droit de la famille (divorce contentieux, consentement mutuel), en droit de la sécurité sociale (contentieux CPAM), en droit pénal (garde à vue, comparution immédiate, CRPC) et en droit public (droit pénitentiaire, contestation de décisions administratives).
Le cabinet se situe 60 rue de Londres à Paris, et est ouvert du lundi au samedi sur rendez vous.
Langues parlées : français, anglais, italien">

    <%# SCSS & JS Links : %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_importmap_tags %>

    <%# Google Recaptcha cdn %>
    <% if Recaptcha.configuration.site_key.present? %>
      <script src="https://www.google.com/recaptcha/api.js" async defer></script>
    <% end %>
  </head>

  <body>
    <%= render 'contacts/contact-form', contact: @contact = Contact.new %>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <% if action_name == 'home' %>
      <% bg_style = "background: no-repeat top -50px left -90px url('#{asset_path('paris_home_bg.png')}'), no-repeat top 600px right -90px url('#{asset_path('elips_bg_right.png')}'), no-repeat top 900px left -60px url('#{asset_path('elips_bg_left.png')}'); background-size: 68%, 50%, 50%;" %>
      <div class="home-container" style="<%= bg_style %>">
        <%= yield %>
      </div>
    <% else %>
      <% bg_style = "background: no-repeat top 300px right -90px url('#{asset_path('elips_bg_right.png')}'), no-repeat top 800px left -60px url('#{asset_path('elips_bg_left.png')}'); background-size: 50%, 50%;" %>
      <div class="pages-container" style="<%= bg_style %>">
        <%= yield %>
      </div>
    <% end %>

    <% unless action_name == 'new' %>
      <%= render 'shared/footer' %>
      <%= render 'shared/footer-mobile' %>
    <% end %>
  </body>
</html>

app/views/pages/cabinet.html.erb
<div class="cabinet-container">
  <div class="valeurs">
    <div class="valeurs-underline">
      <h2 class="zi10">les Valeurs du Cabinet</h2>
      <div id="underliner-valeurs-cabinet"></div>
    </div>
    <div class="valeurs-info">
      <%= image_tag 'yuma-portrait.jpg', class: 'photo-yuma' %>
      <div class="valeurs-info-text">
        <p>Le Cabinet FRUNEAU vous conseille, vous assiste et vous représente devant les juridictions administratives, civiles et pénales, et vous accompagne dans vos démarches auprès des différentes administrations.</p>
        <p><b>Efficacité, Rigueur professionnelle, Bienveillance, Disponibilité, Écoute et Accessibilité</b></p>
        <p>Mes valeurs pour vous accompagner et défendre vos intérêts lorsque vous en aurez le plus besoin.</p>
      </div>
    </div>
  </div>
  <div class="honoraires">
    <div class="underline-honoraire">
      <h2 id='honoraires-section' class="zi10">Les Honoraires</h2>
      <div id="underliner-honoraires-cabinet"></div>
    </div>
    <div class="honoraires-info">
      <div class="honoraires-info-text">
        <p>A l’ouverture de chaque nouveau dossier, une convention d’honoraires écrite et personnalisée sera formalisée.</p>
        <p>Elle définira clairement la mission de Maître FRUNEAU, et les honoraires dus par le client.</p>
        <p>Les prestations juridiques du Cabinet FRUNEAU font l’objet d’une facturation tenant compte de :</p>
        <ul>
          <li>- La nature et la complexité du dossier</li>
          <li>- Le temps consacré à l’affaire</li>
          <li>- L’éventuelle urgence de intervention</li>
          <li>- La nature des diligences à accomplir</li>
          <li>- Les frais exposés par le cabinet</li>
          <li>- La situation financière du client</li>
        </ul>
      </div>
      <%= image_tag 'photo_honoraires.png' %>
    </div>
    <%= render 'components/call-to-action' %>
  </div>
</div>

app/views/pages/contact.html.erb
<div class="contact-container">
  <div class="contact-info">
    <h1 class="zi10">Contact</h1>
    <div id="underliner-contact"></div>

    <div class="contact-info-phone">
      <p>Tel : <%= phone_link %></p>
      <% unless @contact_info.fax.blank? %>
        <p>Fax : <%= @contact_info.fax %></p>
      <% end %>
    </div>

    <p><%= email_link %></p>

    <p>Réception sur RDV uniquement</p>

    <div class="contact-info-address">
      <p><%= @contact_info.street_number %> <%= @contact_info.street_name %></p>
      <p><%= @contact_info.zip_code %> <%= @contact_info.city %></p>
    </div>

    <%= render 'components/call-to-action' %>
  </div>

  <% cache ['contact_map_iframe', @contact_info.google_map_url] do %>
    <iframe src="<%= @contact_info.google_map_url %>"
            width="350" height="540"
            frameborder="0" style="border:1px solid #CCCCCC; border-radius: 5px;"
            allowfullscreen=""
            aria-hidden="false"
            tabindex="0">
    </iframe>
  <% end %>
</div>

app/views/pages/domaines_expertise.html.erb
<div class="domains-container">
  <div class="underline-expertise">
    <h1 class="zi10">Domaines d'Expertise</h1>
    <div id="underliner-domaines-expertise"></div>
  </div>
  <div class="domaine-expertise-cards">
    <div class="domain-card-left">
      <div class="domain-info">
        <h3>Droit des étrangers</h3>
        <ul>
          <li>Demande de titre de séjour auprès de la Préfecture</li>
          <li>Obtention de Visa</li>
          <li>Procédure de regroupement familial</li>
          <li>Demande de naturalisation</li>
          <li>Obligation de quitter le territoire</li>
          <li>Interdiction de retour sur le territoire</li>
        </ul>
        <a class='call-contact-form'>
          Nous contacter
        </a>
      </div>
      <%= image_tag 'SpritesPrestations.png', id: 'globe' %>
    </div>
    <div class="domain-card-right">
      <div class="domain-info">
        <h3>Droit de la famille</h3>
        <ul>
          <li>Divorce contentieux</li>
          <li>Divorce accepté</li>
          <li>Divorce par consentement mutuel</li>
        </ul>
        <a class='call-contact-form'>
          Nous contacter
        </a>
      </div>
      <%= image_tag 'SpritesPrestations.png', id: 'trombones' %>
    </div>
    <div class="domain-card-left">
      <div class="domain-info">
        <h3>Droit administratif</h3>
        <ul>
          <li>Recours contre des décisions administratives</li>
          <li>Recours administratif préalable obligatoire (RAPO)</li>
          <li>Saisine de la Commission d’accès aux documents administratifs (CADA)</li>
          <li>Engagement de la responsabilité d’une personne publique</li>
          <li>Référé liberté</li>
          <li>Référé suspension</li>
        </ul>
        <a class='call-contact-form'>
          Nous contacter
        </a>
      </div>
      <%= image_tag 'SpritesPrestations.png', id: 'conseil-etat' %>
    </div>
    <div class="domain-card-right">
      <div class="domain-info">
        <h3>Droit des personnes</h3>
        <ul>
          <li>Responsabilité civile</li>
          <li>Droit pénal</li>
          <li>Propriété intellectuelle</li>
          <li>Rédaction de contrat</li>
        </ul>
        <a class='call-contact-form'>
          Nous contacter
        </a>
      </div>
      <%= image_tag 'SpritesPrestations.png', id: 'contract' %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<%# ---------------BANNER---------------  %>

<div class="banner">
  <div class="site-title mc900">
    <div class="avocate-underline">
      <h1>Avocate à la Cour</h1>
      <div id="underliner-avocate-home"></div>
    </div>
    <div class="paris-underline">
      <h2>Barreau de Paris</h2>
      <div id="underliner-paris-home"></div>
    </div>
  </div>

  <div class="hero-section mc900">
    <%= image_tag 'yuma_portrait_avatar.jpg', alt: 'photo de Yuma Funeau' %>
    <div class="social-links">
      <%= link_to @contact_info.linkedin_url, target: '_blank' do %>
        <i class="fab fa-linkedin"></i>
      <% end %>
    </div>
  </div>

  <div class="title-pic">
    <div class="site-title">
      <div class="avocate-underline">
        <h1>Avocate à la Cour</h1>
        <div id="underliner-avocate-home"></div>
      </div>
      <div class="paris-underline">
        <h2>Barreau de Paris</h2>
        <div id="underliner-paris-home"></div>
      </div>
    </div>

    <div class="hero-section">
      <%= image_tag 'yuma_portrait_avatar.jpg', alt: 'photo de Yuma Funeau' %>
      <div class="social-links">
        <%= link_to @contact_info.linkedin_url, target: '_blank' do %>
          <i class="fab fa-linkedin"></i>
        <% end %>
      </div>
    </div>
  </div>

  <%= render "components/call-to-action" %>

  <div class="tags-main-container">
    <%= render "components/tags" %>
  </div>

</div>

<%# ---------------PRESENTATION---------------  %>
<div class="prestation-container">
  <div class="presentation" data-controller="presentation" data-presentation-bg-url-value="<%= asset_path('balance_background.png') %>">
    <div class="presentation-info">
      <h2>Présentation :</h2>
      <p>
        Après des études de droit à l'Université de Nice Sophia Antipolis, Maître Fruneau a obtenu un Master 2 Droit et gestion publique de l'université Paris 1 Panthéon Sorbonne.
      </p>
      <p>
        Diplômée de l'EFB (Ecole de Formation du Barreau), elle prête serment auprès du Barreau de Paris et décide d'ouvrir son propre cabinet.
      </p>
      <p>
        Maître Fruneau vous accueille du lundi au samedi dans son cabinet, uniquement sur rendez-vous.
      </p>
      <div class="presentation-langages">
        <h3>Langues parlées :</h3>
        <br>
        <div class="presentation-langages-list">
          <p>Français</p>
          <p>Anglais</p>
          <p>Italien</p>
          <p>Japonais</p>
        </div>
      </div>
    </div>
    <%= image_tag 'balance_justice.png', alt: 'Photo Balance de la justice' %>
  </div>
</div>

<%# ---------------CAROUSEL---------------  %>

<div class="prestation-section">

  <div class="carousel">
    <div class="prestation-underline">
      <h2>Les Prestations</h2>
      <div id="underliner-prestations-home"></div>
    </div>

    <%= render "components/carousel" %>
  </div>

</div>

app/views/pages/mentions_legales.html.erb
<div class="mentions-legales-container">
  <div class="mentions-legales-text">
    <h1 class="zi10">Informations légales</h1><br><br>
    <div id="underliner-legales"></div>
    <div class="mentions-legales-text-responsable">
      <p>Le site « www.fruneau-avocat.com » est édité par Yuma FRUNEAU, Avocate au barreau de Paris, exerçant à titre individuel.</p>
    </div>
    <p>
      Le directeur de la publication est Madame Yuma FRUNEAU, 24 boulevard de Sebastopol 75004 Paris – Tel : 09 81 21 25 05 / Fax : 09 56 65 38 16
    </p><br>
    <div>
      <h4>Informations relatives aux voies de recours en cas de litige :</h4><br>
      <p>Conformément aux dispositions des articles L.612-1 et suivants du Code de la consommation, vous avez la possibilité, en cas de litige, de recourir gratuitement au Médiateur de la consommation auprès du Conseil National des Barreaux (CNB) dont les coordonnées sont les suivantes : CNB, Médiateur à la consommation, 180 boulevard Haussmann - 75008 PARIS ».</p>
      <p>Pour plus d’information, vous pouvez vous connecter sur la plateforme : <a href="https://www.economie.gouv.fr/mediation-conso">https://www.economie.gouv.fr/mediation-conso</a></p><br>
      <h4>Informations relatives au traitement des données :</h4><br>
      <p>En application des articles 13 et 14 du Règlement européen Général sur la Protection des Données (2016/679) et de l’article 32 de la loi Informatique et Libertés du 6 janvier 1978 modifiée, le Directeur de Publication du Site vous informe que :</p>
      <p>a. (Qui protège ?) : Le responsable du fichier est Me FRUNEAU, 24 boulevard de Sebastopol 75004 PARIS, Tel : 09 81 21 25 05 / Fax : 09 56 65 38 16 avocat@fruneau-avocat.com ;</p>
      <p>b. (Qu’est-ce qui est protégé ?) : L’ensemble de vos données personnelles ;</p>
      <p>c. (Pourquoi ? A quelles fins ?) : Pour la protection de votre vie privée, dans le cadre du traitement de votre dossier, qu’il s’agisse d’un dossier juridique, judiciaire ou d’arbitrage ;</p>
      <p>d. (Où ?) : Dans un registre, tenu par Me FRUNEAU ;</p>
      <p>e. (Quand et jusqu’à quand) : Vos données sont traitées et conservées par Me FRUNEAU, dès votre prise d’attache, y compris pour le simple établissement d’un devis ou lors de la prise d’un rendez-vous ;</p>
      <p>f. Elles ne seront conservées que 8 semaines, dans l’hypothèse où le rendez-vous ne serait pas honoré.</p> 
      <p>g. Dans tous les autres cas, elles seront conservées pendant un délai de 5 années à compter du dernier acte juridique ou judiciaire réalisé par Me FRUNEAU ;</p>
      <p>h. (Comment ?) : Par des locaux et un système informatique protégés et sécurisés ;</p><br>
      <p>Me FRUNEAU vous rappelle que vous disposez d’un droit d’accès, de limitation, de rectification ou d’effacement de vos données personnelles, en vous adressant à Me FRUNEAU, responsable dudit traitement, par courrier recommandé au 24 boulevard de Sebastopol 75004 Paris.</p>
      <p>Dans l’hypothèse où vous considéreriez que vos données ne sont pas protégées, vous avez la faculté de former une réclamation auprès de la CNIL, 3 Place de Fontenoy - TSA 80715 - 75334 PARIS CEDEX 07.</p>
    </div><br>
    <h4>Informations relatives à l’hébergement :</h4><br>
    <p>
      Le site a été réalisé par <%= link_to 'Jérémy BRD', 'https://www.jeremybrd.dev' %>
    </p>
    <p>
      Le site est hébergé par Salesforce.com Sarl, Route de la Longeraie 9, Morges, 1110, Switzerland, attn: Director, EMEA Sales Operations, with a copy to attn.: Legal Department - Service Juridique, 3 Avenue Octave Gréard, 75007 Paris, France.Tél: +33172109400
    </p>
    <div class="mentions-legales-text-credit-photo">
      <p><a href="https://unsplash.com/@aleksiii?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Alexander</a> on <a href="https://unsplash.com/s/photos/paris?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></p>

      <p><a href="https://unsplash.com/@sctgrhm?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Scott Graham</a> on <a href="https://unsplash.com/s/photos/law?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></p>

      <p><a href="https://unsplash.com/@tingeyinjurylawfirm?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Tingey Injury Law Firm</a> on <a href="https://unsplash.com/s/photos/law?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></p>

      <p><a href="https://unsplash.com/@stevenlasry?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Steven Lasry</a> on <a href="https://unsplash.com/s/photos/conseil-d%C3%A9tat?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></p>
      <p>Yann Le Tutour</p>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer-mobile.html.erb
<div class="footer-mobile">
  <hr>

  <div class="social-media-mobile-footer">
    <%= link_to @contact_info.linkedin_url, target: '_blank' do %>
      <i class="fab fa-linkedin"></i>
    <% end %>

    <%= link_to 'Mentions Légales', mentions_legales_path %>
  </div>

  <p><%= email_link %></p>

  <hr>

  <div class="footer-mobile-rights">
    <i class="far fa-copyright"></i>

    <%= copiright_year_update %>
    <p id="yuma-footer-mobile"><%= @contact_info.full_name.upcase %> by</p>
    <%= link_to 'Jérémy BRD', 'https://www.jeremybrd.dev' %>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <%# ---------------CONTACT SECTION (LEFT CONTENT)---------------  %>
  <div class="footer-contact-section">
    <div class="footer-brand">
      <%= image_tag 'logo_bigger.png' %>
      <h2><%= @contact_info.full_name.upcase %></h2>
    </div>

    <div class="footer-info-contact">
      <div class="footer-info-contact-address">
        <p><%= @contact_info.street_number %> <%= @contact_info.street_name %></p>
        <p><%= @contact_info.zip_code %> <%= @contact_info.city %></p>
      </div>

      <div class="footer-info-contact-tel">
        <p>Tel : <%= phone_link %></p>
        <% unless @contact_info.fax.blank? %>
          <p>Fax : <%= @contact_info.fax %></p>
        <% end %>
      </div>

      <p><%= email_link %></p>
    </div>
  </div>

  <%# ---------------SITE PLAN SECTION (MIDDLE CONTENT)---------------  %>
  <div class="footer-site-plan-section">
    <div class="footer-underline">
      <h3>PLAN DU SITE :</h3>
      <div id="underliner-footer"></div>
    </div>

    <div class="footer-site-plan-links">
      <%= link_to 'Le Cabinet', cabinet_path %>
      <%= link_to 'Les Domaines d\'Expertise', domaines_expertise_path %>
      <%= link_to 'Les Actualités Juridiques', '#' %>
      <%= link_to 'Contact', contact_path %>
    </div>
  </div>

  <%# ---------------LEGAL SECTION (RIGHT CONTENT)---------------  %>
  <div class="footer-legal-section">
    <div class="footer-social-links">
      <%= link_to @contact_info.linkedin_url, target: '_blank' do %>
        <i class="fab fa-linkedin"></i>
      <% end %>
    </div>

    <%= link_to 'Mentions Légales', mentions_legales_path %>

    <div class="footer-rights">
      <i class="far fa-copyright"></i>
      <%= copiright_year_update %>
      <p><%= @contact_info.full_name.upcase %> by</p>
      <%= link_to 'Jérémy BRD', 'https://www.jeremybrd.dev' %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="home-navbar">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag 'logo_bigger.png' %>

    <div class="brand-text">
      <span><%= @contact_info.first_name.upcase %></span>
      <span><%= @contact_info.last_name.upcase %></span>
    </div>
  <% end %>

  <div class="home-navbar-nav-links">
    <div class="dropdown-cabinet">
      <%= link_to cabinet_path, class: 'nav-link-home dropdown-cabinet-btn' do %>
        LE CABINET
      <% end %>

      <div class="linker"></div>

      <div class="dropdown-cabinet-content">
        <%= link_to 'LES VALEURS DU CABINET', cabinet_path %>
        <%= link_to 'LES HONORAIRES', '/cabinet#honoraires-section', id: 'lthonoraires' %>
      </div>
    </div>

    <%= link_to 'LES DOMAINES D\'EXPERTISE', domaines_expertise_path, class: 'nav-link-home' %>
    <%= link_to 'CONTACT', contact_path, class: 'nav-link-home' %>
  </div>

  <div class="hamburger" data-controller="hamburger">
    <div class="circle-menu" data-hamburger-target="menu">
      <%= link_to 'LE CABINET', cabinet_path, class: 'links-circle', id: 'mb10vh' %>
      <%= link_to 'LES DOMAINES D\'EXPERTISE', domaines_expertise_path, class: 'links-circle', id: 'mb10vh' %>
      <%= link_to 'CONTACT', contact_path, class: 'links-circle' %>
    </div>

    <div class="btn-circle" data-hamburger-target="button" data-action="click->hamburger#toggle">
      <div class="line"></div>
      <div class="line"></div>
      <div class="line"></div>
    </div>
  </div>
</div>